<?php

/**
 * @file Contains hooks for the twig_components module.
 */

use Drupal\Core\Asset\AttachedAssets;

/**
 * Implements hook_library_info_build().
 */
function twig_components_library_info_build() {
  $libraries = [];
  /** @var \Drupal\twig_components\TwigComponentPluginManager $manager */
  $manager = \Drupal::service('plugin.manager.twig_component');
  foreach ($manager->getDefinitions() as $plugin_id => $definition) {
    /** @var \Drupal\twig_components\TwigComponentInterface $instance */
    $instance = $manager->createInstance($plugin_id, $definition);
    $name = str_replace('twig_components/', '', $instance->getLibraryName());
    $libraries[$name] = $instance->getLibraryDefinition();
  }
  return $libraries;
}

/**
 * Implements hook_element_info_alter().
 */
function twig_components_element_info_alter(&$types) {
  $types['text_format']['#pre_render'][] = '_twig_components_pre_render_text_format';
}

/**
 * Pre-render callback for text_format elements.
 */
function _twig_components_pre_render_text_format($variables) {
  if (\Drupal::moduleHandler()->moduleExists('ckeditor')) {
    // Get all twig component libraries.
    $scripts = [];
    /** @var \Drupal\twig_components\TwigComponentPluginManager $manager */
    $manager = \Drupal::service('plugin.manager.twig_component');
    /** @var \Drupal\Core\Asset\AssetResolver $asset_resolver */
    $asset_resolver = \Drupal::service('asset.resolver');
    /** @var \Drupal\Core\Asset\JsCollectionRenderer $js_renderer */
    $js_renderer = \Drupal::service('asset.js.collection_renderer');
    $renderer = \Drupal::service('renderer');
    foreach ($manager->getDefinitions() as $plugin_id => $definition) {
      /** @var \Drupal\twig_components\TwigComponentInterface $instance */
      $instance = $manager->createInstance($plugin_id, $definition);
      $assets = new AttachedAssets();
      $assets->setLibraries([$instance->getLibraryName()]);
      list($js_assets_header, $js_assets_footer) = $asset_resolver->getJsAssets($assets, FALSE);
      // Render their assets and add the HTML as a Drupal setting.
      $build = [];
      $build[] = $js_renderer->render($js_assets_header);
      $build[] = $js_renderer->render($js_assets_footer);
      $scripts[$definition['tag']] = $renderer->renderRoot($build);
    }
    $variables['#attached']['drupalSettings']['twigComponentsCKEditorScripts'] = $scripts;
    $variables['#attached']['library'][] = 'twig_components/ckeditor';
  }
  return $variables;
}
